version: '3.9'

services:
  postgres_test:
    image: postgres:16.0-alpine
    container_name: postgres_test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    ports:
      - "54321:5432"
